<?php
$identificador = isset($_GET['tarjeta']) ? $_GET['tarjeta'] : '';
if ($identificador == 'ERP') {

    require('SolucionesDetail.php');
    $descripcionAyudaTitulo=['Simplifica y optimiza operaciones', 'Automatiza tareas y aumenta la eficiencia', 'Fomenta la colaboración y la comunicación', 'Proporciona datos reales y relevantes', 'Permite personalizaciones según necesidades', 'Brinda información clave para tomar decisiones'];
    
    $descripcionAyuda = ['Nuestro sistema de ERP centraliza y simplifica la gestión de todos los aspectos clave de tu negocio, desde la planificación de recursos hasta la gestión de inventarios y ventas. Obtén un control integral y eficiente de tus procesos empresariales.', 
    'Con nuestro sistema de ERP, podrás automatizar tareas repetitivas y liberar tiempo valioso.',
    'Nuestro ERP promueve la colaboración entre departamentos al centralizar los datos y compartir información en tiempo real.',
    'Reduce la duplicación de datos, mejora la comunicación interna y agiliza los flujos de trabajo para un mayor rendimiento en equipo.',
    'Adaptamos nuestro sistema de ERP a las particularidades de tu negocio. Con módulos adicionales y personalizables, puedes obtener funcionalidades específicas que se ajusten a tus requerimientos, ya sea control de inventario, gestión de proyectos o relacione con los clientes.',
    'Obtén informes y análisis detallados para evaluar el rendimiento de tu negocio. Accede a métricas clave, indicadores de rendimiento y estadísticas en tiempo real para tomar decisiones estratégicas basadas en datos confiables.'];

    $preguntasFrecuentes = ['¿Cómo puedo personalizar el sistema de ERP para adaptarlo a las necesidades específicas de mi negocio?', '¿Cómo puedo garantizar la seguridad de mis datos en el sistema de ERP?', '¿Cómo puedo garantizar la seguridad de mis datos en el sistema de ERP?'];

    $respuestas = ['En Cleversoft, entendemos la importancia de la personalización. Nuestro sistema de ERP ofrece módulos adicionales y personalizables que te permiten ajustar el sistema según tus requisitos particulares. Ya sea que necesites funcionalidades específicas para el control de inventario, seguimiento de proyectos o gestión de relaciones con los clientes (CRM), trabajaremos contigo para configurar el sistema de ERP de manera que se adapte perfectamente a tu negocio.', 'La seguridad de tus datos es nuestra máxima prioridad. Nuestro sistema de ERP utiliza medidas de seguridad robustas para proteger tu información empresarial. Implementamos tecnologías de encriptación y protocolos de seguridad avanzados para garantizar la confidencialidad y la integridad de tus datos. Además, realizamos copias de seguridad periódicas para asegurar la disponibilidad y la recuperación de la información en caso de algún incidente.', 'Nos comprometemos a brindarte un sólido soporte técnico en cada etapa del proceso. Nuestro equipo de expertos estará disponible para responder tus preguntas, resolver problemas y proporcionarte la asistencia necesaria durante la implementación y el uso continuo del sistema de ERP. Además, ofrecemos capacitación detallada para tu equipo, asegurándonos de que puedas aprovechar al máximo todas las funcionalidades y beneficios que nuestro sistema de ERP tiene para ofrecer.'];

    $erp = new SolucionesDetail('Clever ERP', 'Sistema de planificación de </br> recursos empresariales', 'Gestión optimizada para empresas: simplifica operaciones y potencia tu crecimiento con nuestro sistema de ERP','Potencia tu negocio con nuestro sistema de ERP', 
    'Nuestro sistema de ERP es una solución integral diseñada para optimizar y simplificar la gestión de todos los aspectos clave de los negocios. </br>Se trata de una plataforma centralizada que integra y administra todos los procesos empresariales, abarcando desde la planificación de recursos hasta la gestión de inventarios, ventas, finanzas y más.
    </br></br>Ofrecemos una visión panorámica y en tiempo real de todas las operaciones comerciales, lo que te permitirá tomar decisiones más informadas y estratégicas.
    Contamos con procesos para automatizar tareas repetitivas y mejorar la eficiencia operativa en toda tu organización.</br> Esto se logra gracias a que todos los datos se almacenan en una base de datos
    centralizada y se comparten entre diferentes funciones y equipos, fomentando así una mejor colaboración entre departamentos.
    Con esto, se reduce la duplicación de datos, se mejora la comunicación interna y se agilizan los flujos de trabajo.
    </br></br>Además, ofrecemos módulos adicionales y personalizables para adaptarse a las necesidades específicas. Independientemente de si se requieren funcionalidades específicas para el control de inventario, seguimiento de proyectos, gestión de relaciones con los clientes (CRM) u otros aspectos empresariales, nuestro sistema de ERP puede configurarse según requisitos particulares.
    </br>Otra ventaja de nuestro ERP es la generación de informes y análisis detallados con el cual se puede obtener una comprensión profunda del rendimiento de negocio, accediendo a métricas clave, indicadores de rendimiento y estadísticas en tiempo real. De esta manera, se logra evaluar la rentabilidad, identificar áreas de mejora y tomar decisiones estratégicas basadas en datos confiables.',
    'Nuestro equipo de especialistas en tecnología, arquitectura empresarial y transformación está aquí para potenciar negocios, utilizando la tecnología y la innovación como herramientas para la reinvención.',$descripcionAyudaTitulo, $descripcionAyuda, $preguntasFrecuentes, $respuestas);


} else if ($identificador == 'CLUB') {
    require('SolucionesDetail.php');
    $preguntasFrecuentes = ['¿Cómo puede nuestro club de fútbol beneficiarse de CleverClub en la gestión de entradas y eventos?', '¿Cómo puede nuestro club de fútbol beneficiarse de CleverClub en la gestión de entradas y eventos?', '¿Cómo puede nuestro club de fútbol beneficiarse de ClubMaster en la gestión de entradas y eventos?'];
    $respuestas = ['CleverClub ofrece una plataforma completa para la gestión de entradas y eventos en tu club. Podrás agilizar la venta de entradas, controlar el acceso a los partidos y eventos, generar informes detallados y optimizar la experiencia de los aficionados. Nuestro sistema te ayudará a mejorar la organización de eventos y maximizar los ingresos.', 'CleverClub simplifica la gestión de la membresía de socios y abonados. Podrás mantener un registro actualizado de los socios, gestionar las cuotas, enviar recordatorios de pago y generar informes financieros detallados. El sistema también ofrece funciones de comunicación personalizada para mantener una relación cercana con tus socios y fomentar la participación en el club.', 'Nos comprometemos a brindar un sólido soporte y asistencia técnica. Nuestro equipo estará disponible para responder tus preguntas, resolver problemas y proporcionarte orientación en cada etapa de la implementación y el uso del sistema. Además, ofrecemos capacitación detallada para garantizar que aproveches al máximo todas las funcionalidades de ClubMaster.'];

    $club = new SolucionesDetail('Clever Club', 'Sistema integral para la gestión de clubes deportivos', 'Nuestro Clever CLUB es una solución integral diseñada para optimizar y simplificar la gestión de todas las áreas clave en el ámbito deportivo. Desde la administración de ventas de entradas hasta la habilitación de partidos, gestión de sectores y una web para auto gestión de los socios, nuestro sistema abarca todas las necesidades específicas de los clubes de fútbol en un único y poderoso software.
    Con nuestro ERP, podrás gestionar de manera eficiente y centralizada la venta de entradas para los partidos. Además, tendrás la capacidad de habilitar y programar partidos, asignando fechas, horarios, sectores y sedes, optimizando así la organización de las competencias.
    El sistema también ofrece funcionalidades específicas para la gestión de sectores, lo que te permitirá asignar áreas y asientos a los socios y no socios, garantizando un control adecuado de la capacidad y brindando una experiencia mejorada en los eventos deportivos.
    Con nuestra solución, también podrás gestionar la membresía de socios, llevar un registro actualizado de las cuotas y pagos, así como enviar comunicaciones personalizadas y mantener una relación cercana con tus seguidores y socios.', 'Domina el juego con nuestro ERP para clubes: gestión integral y victoria asegurada', 'https://www.instagram.com/p/Cn7kIX3OwjT/', 'Simplifica y centraliza la gestión: Nuestro ERP para clubes de fútbol te permite simplificar y centralizar la gestión de todas las áreas operativas, desde la venta de entradas hasta la habilitación de partidos y la administración del kiosco del club. Ahorra tiempo y recursos al tener todo en un solo sistema.
    Optimiza la experiencia de los aficionados: Proporciona una experiencia excepcional a los aficionados y socios con la gestión eficiente de la venta de entradas, asignación de asientos, control de acceso y mejora en la atención en el kiosco del club. Impulsa la fidelidad de tus seguidores y genera ingresos adicionales.
    Gestiona la membresía y los pagos: Lleva un control preciso de la membresía de socios, las cuotas y los pagos. Envía comunicaciones personalizadas, mantiene una base de datos actualizada y fortalece la relación con tus seguidores, fomentando la participación y el compromiso con el club.', '../imagenes/imagen', $preguntasFrecuentes, $respuestas);
} else if ($identificador == 'SCA') {
    echo '<p>SCA</p>';
} else if ($identificador == 'CRM') {
    echo '<p>CRM</p>';
} else {
    echo '<p>TODOS</p>';
}
